### ISSUE TITLE
示例代码建议补充异常处理逻辑

### ISSUE THREAD

**Issue by charmingzuo** [TheNorthMemory/wechatpay-axios-plugin#1]
建议补充异常处理逻辑代码示例，以提醒开发者应当小心处理通信异常

**Comment by charmingzuo** [comment]
👍 我看到`promise style`已经加了`.catch`处理，但`async/await`还没有加`try-catch`处理，建议也加上哈

**Comment by TheNorthMemory** [comment]
嗯，`async/await` 仅添加了`try catch`一例，程序出错是好事啊😄

**Comment by TheNorthMemory** [comment]
all done
