### ISSUE TITLE
在进行订单查询的时候，订单号不能更新

### ISSUE THREAD

**Issue by ali-pay** [TheNorthMemory/wechatpay-axios-plugin#10]
### 在进行订单查询的时候，订单号不能更新

![Snipaste_2021-02-20_15-34-24](https://user-images.githubusercontent.com/54493910/108587916-7082bb00-7391-11eb-9376-c893adb645e9.png)

![Snipaste_2021-02-20_15-31-39](https://user-images.githubusercontent.com/54493910/108587926-78425f80-7391-11eb-9175-bc754ee47a6e.png)

**Comment by TheNorthMemory** [comment]
我来看看，稍等

**Comment by TheNorthMemory** [comment]
动态 `url_template` 式的参数这里有缺陷，建议使用属性式即 `.outTradeNo['CeGHB...wfF']` 调用，下一个版本我尝试调整一下实现方式。

**Comment by TheNorthMemory** [comment]
v0.4.0 版本做了重构，废弃了 `withEntities` 方法，改为HTTP DELETE/GET/POST/PUT/PATCH时传参数，如：

```diff
wxpay.v3.pay.transactions.outTradeNo["{txid}"]
- .withEntities({ txid: txid })
- .get({ params: { mchid: MCH_ID } })
+ .get({ params: { mchid: MCH_ID }, txid: txid })
```
以上更新保证了每次重入时，`/v3/pay/transactions/out-trade-no/{txid}` 方法对象的`{txid}`仅在HTTP调用时替换，不会干扰二次变参重入。

**Comment by TheNorthMemory** [comment]
npmjs上 v0.4.0 已发布。

**Comment by ali-pay** [comment]
谢谢！
