### ISSUE TITLE
The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined

### ISSUE THREAD

**Issue by NiBoTe** [TheNorthMemory/wechatpay-axios-plugin#14]
The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined，
接口再浏览器上看已经返回成功了。但是代码还是报错

**Comment by TheNorthMemory** [comment]
这个异常信息，来自未正确配置 v3的 `privateKey`及v2的`merchant.key`，最新`README`上添加了说明，建议阅读一下官方文档 [私钥和证书](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay3_1.shtml)

**Comment by NiBoTe** [comment]
我这样传不行吗？证书我用工具生成了的。然后我掉native 接口浏览器已经返回了 二维码链接，也可以正常支付。
求解。





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TheNorthMemory/wechatpay-axios-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月11日(星期四) 下午4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TheNorthMemory/wechatpay-axios-plugin] The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined (#14)





 
这个异常信息，来自未正确配置 v3的 privateKey及v2的merchant.key，最新README上添加了说明，建议阅读一下官方文档 私钥和证书

**Comment by NiBoTe** [comment]
![image](https://user-images.githubusercontent.com/24713845/110756910-bc849980-8285-11eb-9369-1cf55e798722.png)
apiv3 秘钥我设置过了

**Comment by TheNorthMemory** [comment]
`APIv3密钥` 在初始化里没有用到，这个不是`privateKey`，`privateKey`指得是证书,翻译出来叫`私钥`，跟`密钥`一字相差，但完全不是一个东东。

Native付款码链接你应该用的是 v2接口生成的吧。。。

**Comment by TheNorthMemory** [comment]
`APIv3密钥` 在初始化里没有用到，这个不是`privateKey`，`privateKey`指得是证书,翻译出来叫`私钥`，跟`密钥`一字相差，但完全不是一个东东。

Native付款码链接你应该用的是 v2接口生成的吧。。。

**Comment by NiBoTe** [comment]
![image](https://user-images.githubusercontent.com/24713845/110759225-58afa000-8288-11eb-9a4a-9a6d4158214f.png)
掉这个接口生成的。

**Comment by NiBoTe** [comment]
![image](https://user-images.githubusercontent.com/24713845/110762027-56027a00-828b-11eb-9596-405ebfe0263c.png)这样传也不行。。。。

**Comment by TheNorthMemory** [comment]
嗯，你这个应该是云开发环境，`fs.readFileSync` 一般读取的时候会有差异，建议本地开发环境，记事本或者编辑器，把文件内容读取出来，内容是带换行符的字符串，其中`换行符`不能少。
