### ISSUE TITLE
支持h5支付吗

### ISSUE THREAD

**Issue by dingyong666** [TheNorthMemory/wechatpay-axios-plugin#18]
APPID、MCHID、自己设置的32位KEY， 我看php sdk有个版本，只需要上面那3个参数即可H5

**Comment by TheNorthMemory** [comment]
> APPID、MCHID、自己设置的32位KEY， 我看php sdk有个版本，只需要上面那3个参数即可H5

你说的这个指的是v2版的H5统一下单，支持的示例代码如下：

```js
wxpay.v2.pay.unifiedorder({
  appid: 'wx2421b1c4370ec43b',
  attach: '支付测试',
  body: 'H5支付测试',
  mch_id: '10000100',
  nonce_str: Formatter.nonce(),
  notify_url: 'http://wxpay.wxutil.com/pub_v2/pay/notify.v2.php',
  openid: 'oUpF8uMuAJO_M2pxb1Q9zNjWeS6o',
  out_trade_no: '1415659990',
  spbill_create_ip: '14.23.150.211',
  total_fee: 1,
  trade_type: 'MWEB',
  scene_info: JSON.stringify({
    h5_info: {
      type:"IOS",
      app_name: "王者荣耀",
      package_name: "com.tencent.tmgp.sgame"
    }
  }),
}).then(console.info).catch(console.error);
```

APIv3版如下：

```js
wxpay.v3.pay.transactions.h5({
  "time_expire": "2018-06-08T10:34:56+08:00",
  "amount": {
    "total": 100,
    "currency": "CNY"
  },
  "mchid": "1230000109",
  "description": "Image形象店-深圳腾大-QQ公仔",
  "notify_url": "https://www.weixin.qq.com/wxpay/pay.php",
  "out_trade_no": "1217752501201407033233368018",
  "goods_tag": "WXG",
  "appid": "wxd678efh567hg6787",
  "attach": "自定义数据说明",
  "detail": {
    "invoice_id": "wx123",
    "goods_detail": [{
      "goods_name": "iPhoneX 256G",
      "wechatpay_goods_id": "1001",
      "quantity": 1,
      "merchant_goods_id": "商品编码",
      "unit_price": 828800
    }, {
      "goods_name": "iPhoneX 256G",
      "wechatpay_goods_id": "1001",
      "quantity": 1,
      "merchant_goods_id": "商品编码",
      "unit_price": 828800
    }],
    "cost_price": 608800
  },
  "scene_info": {
    "device_id": "013467007045764",
    "store_info": {
      "address": "广东省深圳市南山区科技中一道10000号",
      "area_code": "440305",
      "name": "腾讯大厦分店",
      "id": "0001"
    },
    "h5_info": {
      "app_name": "王者荣耀",
      "app_url": "https://pay.qq.com",
      "bundle_id": "com.tencent.wzryiOS",
      "package_name": "com.tencent.tmgp.sgame",
      "type": "iOSAndroidWap"
    },
    "payer_client_ip": "14.23.150.211"
  },
  "settle_info": {
    "profit_sharing": false
  }
}).then(console.info).catch(console.error);
```

**Comment by dingyong666** [comment]
@TheNorthMemory  那如果使用 v2 的 h5 ，初始化 new Wechatpay 的配置该如何写

**Comment by TheNorthMemory** [comment]
> @TheNorthMemory 那如果使用 v2 的 h5 ，初始化 new Wechatpay 的配置该如何写

```js
const wxpay = new Wechatpay({
  mchid: 'your_merchant_id',
  serial: 'any',
  privateKey: 'any',
  certs: {
    any: undefined,
  },
  secret: 'your_merchant_secret_key_string',
})
```

`your_merchant_id`, `your_merchant_secret_key_string` 替换为你的即可。

**Comment by TheNorthMemory** [comment]
README文档上，有命令行的用法示例，初始化参数 `-c.` 写着如下：

```
./node_modules/.bin/wxpay v2/tools/authcodetoopenid \
  -c.mchid 1230000109 \
  -c.serial any \
  -c.privateKey any \
  -c.certs.any \
  -c.secret your_merchant_secret_key_string \
  -d.appid wxd678efh567hg6787 \
  -d.mch_id 1230000109 \
  -d.nonce_str 5K8264ILTKCH16CQ2502SI8ZNMTM67VS \
  -d.auth_code 120061098828009406
```

**Comment by dingyong666** [comment]
wxpay.v2.pay.unifiedorder    是 jsapi 吧 ，看还需要一个 openid 参数，应该是只能在 微信内置浏览支付的，然后我又把 openid 设置 空，订单是创建成功了，但是浏览器打开提示参数错误，

想的是应该 pc 上扫码，手机上访问url 调用微信支付这样~   先谢大佬！

**Comment by dingyong666** [comment]
wxpay.v2.pay.unifiedorder    是 jsapi 吧 ，看还需要一个 openid 参数，应该是只能在 微信内置浏览支付的，然后我又把 openid 设置 空，订单是创建成功了，但是浏览器打开提示参数错误，

想的是应该 pc 上扫码，手机上访问url 调用微信支付这样~   先谢大佬！

**Comment by TheNorthMemory** [comment]
手机上扫码是native付功能，v2都是 `pay.unifiedorder`，你需要去翻官方的牌子，找文档；建议你直接用`wxpay.v3.pay.transactions.native` 直接驱动

**Comment by dingyong666** [comment]
@TheNorthMemory  换成了 v3的 

`const {Wechatpay, Formatter} = require('wechatpay-axios-plugin')
const fs = require('fs')

let privateKey = fs.readFileSync('pem/apiclient_key.pem').toString().replace(/\n/g,'');
console.log(privateKey)
let cert = fs.readFileSync('pem/apiclient_cert.pem').toString().replace(/\n/g,'');
console.log(cert)

const wxpay = new Wechatpay({
    mchid: '111111',
    serial: '4034C472D3C81CCA157C5837B7186E366886EA75',
    privateKey: '-----BEGIN PRIVATE KEY-----\n' + privateKey + '\n-----END PRIVATE KEY-----',
    certs: {
        '4034C472D3C81CCA157C5837B7186E366886EA75': '-----BEGIN CERTIFICATE-----\n' + cert + '\n-----END CERTIFICATE-----',
    },
    // APIv2参数 >= 0.4.0 开始支持
    secret: '111111111111111111111111',
    // 注： 如果不涉及资金变动，如仅收款，merchant参数可选，仅需 `secret` 一个参数，注意其为v2版的。
    // APIv2沙箱环境地址
    // baseURL: 'https://api.mch.weixin.qq.com/sandboxnew',
    // 建议初始化设置此参数，详细说明见Axios官方README
    // maxRedirects: 0,

})

let data = {
    appid: '111111',
    mchid: '111111',
    description: 'test description',
    out_trade_no: '12177513233368018',
    notify_url: 'https://pay.123.cn/test',
    amount: {
        total: 100,
        currency: 'CNY'
    }
}
wxpay.v3.pay.transactions.native
    .post(data)
    .then(({data: {code_url}}) => console.info(code_url))
    .catch(function (e) {
        console.log(e)
    })`

证书里面是去掉头、尾的。这样写感觉没问题了，但是报错》。。

`
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareAsymmetricKey (internal/crypto/keys.js:299:9)
    at preparePublicOrPrivateKey (internal/crypto/keys.js:312:10)
    at Verify.verify (internal/crypto/sig.js:175:7)
    at Function.verify (E:\project\gopay\node_modules\wechatpay-axios-plugin\lib\rsa.js:73:73)
    at verifier (E:\project\gopay\node_modules\wechatpay-axios-plugin\lib\interceptor.js:122:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
`

**Comment by TheNorthMemory** [comment]
好几个问题，建议先用一下cli工具，看下工具是怎么怎么跑的。。。

入参上，证书部分支持直接buffer输入，例如：

```js
let privateKey = fs.readFileSync('pem/apiclient_key.pem');
const wxpay = new Wechatpay({privateKey});
```

**Comment by dingyong666** [comment]
> 好几个问题，建议先用一下cli工具，看下工具是怎么怎么跑的。。。
> 
> 入参上，证书部分支持直接缓冲输入，例如：
> 
> ```js
> 让 privateKey  =  fs 。readFileSync （'pem / apiclient_key.pem' ）; 
> const  wxpay  = 新的 Wechatpay （{ privateKey } ）;
> ```

证书我试用 readFileSync  传 buffer ，还是一样的错误

**Comment by TheNorthMemory** [comment]
先把 README 仔细看一下，初始化需要的参数，错误提示 `interceptor.js:122:11` 说明你没给对平台证书，你要先 **起步** 一下。

> 初始化字典说明如下：
>
> - `mchid` 为你的商户号，一般是10字节纯数字
> - `serial` 为你的商户证书序列号，一般是40字节字符串
> - `privateKey` 为你的商户私钥证书，一般是通过官方证书生成工具生成的文件名是`apiclient_key.pem`文件，支持纯字符串或者文件流`buffer`格式
> - `certs{[serial_number]:string}` 为通过下载工具下载的平台证书`key/value`键值对，键为平台证书序列号，值为平台证书pem格式的纯字符串或者文件流`buffer`格式
> - `secret` 为APIv2版的`密钥`，商户平台上设置的32字节字符串
> - `merchant.cert` 为你的商户证书,一般是文件名为`apiclient_cert.pem`文件，支持纯字符串或者文件流`buffer`格式
> - `merchant.key` 为你的商户私钥证书，一般是通过官方证书生成工具生成的文件名是`apiclient_key.pem`文件，支持纯字符串或者文件流`buffer`格式
> - `merchant.passphrase` 一般为你的商户号
> - `merchant.pfx` 为你的商户`PKCS12`格式的证书，文件名一般为`apiclient_cert.p12`，支持二进制文件流`buffer`格式

**Comment by dingyong666** [comment]
> 先把 README 仔细看一下，初始化需要的参数，错误提示 `interceptor.js:122:11` 说明你没给对平台证书，你要先 **起步** 一下。
> 
> > 初始化字典说明如下：
> > 
> > * `mchid` 为你的商户号，一般是10字节纯数字
> > * `serial` 为你的商户证书序列号，一般是40字节字符串
> > * `privateKey` 为你的商户私钥证书，一般是通过官方证书生成工具生成的文件名是`apiclient_key.pem`文件，支持纯字符串或者文件流`buffer`格式
> > * `certs{[serial_number]:string}` 为通过下载工具下载的平台证书`key/value`键值对，键为平台证书序列号，值为平台证书pem格式的纯字符串或者文件流`buffer`格式
> > * `secret` 为APIv2版的`密钥`，商户平台上设置的32字节字符串
> > * `merchant.cert` 为你的商户证书,一般是文件名为`apiclient_cert.pem`文件，支持纯字符串或者文件流`buffer`格式
> > * `merchant.key` 为你的商户私钥证书，一般是通过官方证书生成工具生成的文件名是`apiclient_key.pem`文件，支持纯字符串或者文件流`buffer`格式
> > * `merchant.passphrase` 一般为你的商户号
> > * `merchant.pfx` 为你的商户`PKCS12`格式的证书，文件名一般为`apiclient_cert.p12`，支持二进制文件流`buffer`格式

弄好了，中间最混淆搞错的就是 certs 的配置，需要单独生成一个证书

`certs: {
        // 使用 cli 生成的
        // wxpay crt -m XXX -s {官网的证书序列号} -f ../../test/pem/apiclient_key.pem -k {32位key} -o
        '36736A4D01F0056B033693E40B6DB995D2A9B6XX': fs.readFileSync('pem/wechatpay_36736A4D01F0056B033693E40B6DB995D2A9B6XX.pem'),
    },`

**Comment by TheNorthMemory** [comment]
赞，成功又引导一位同学进入v3时刻。

**Comment by dingyong666** [comment]
@TheNorthMemory   微信v3成功后的 回调数据，有什么现成的方式解密出通知数据resource吗

**Comment by TheNorthMemory** [comment]
> @TheNorthMemory 微信v3成功后的 回调数据，有什么现成的方式解密出通知数据resource吗

https://github.com/TheNorthMemory/wechatpay-axios-plugin/blob/300988025bff43e4196766150a27ebf75cc55613/bin/cli/cert.js#L73-L74

参考上述实现，`Ae.decrypt` 方法
