### ISSUE TITLE
功能支持：微信验签

### ISSUE THREAD

**Issue by victorykong** [TheNorthMemory/wechatpay-axios-plugin#31]
微信v3验签是否有支持的方法？

**Comment by victorykong** [comment]
@TheNorthMemory

**Comment by TheNorthMemory** [comment]
https://github.com/TheNorthMemory/wechatpay-axios-plugin/blob/674d1dab1d73170756176a9b71bc517ca5702a26/lib/decorator.js#L168

即是验签逻辑
