### ISSUE TITLE
h5支付：支付成功回调通知同时去查询，进程假死，阻塞所有请求

### ISSUE THREAD

**Issue by victorykong** [TheNorthMemory/wechatpay-axios-plugin#32]
根据日志看，如果微信异步通知和用户前端主动触发订单查询，会造成程序卡死

**Comment by victorykong** [comment]
一开始以为是数据库锁住了，两个 controller 调同一个 service 去更新订单状态，但数据库未排查到任何锁。打日志的时候发现，如图箭头处，无打印。
![image](https://user-images.githubusercontent.com/50655436/124353528-98d0cf00-dc39-11eb-8ddf-96376cf93867.png)

**Comment by victorykong** [comment]
@TheNorthMemory 是否可以协助看看，谢谢

**Comment by victorykong** [comment]
![image](https://user-images.githubusercontent.com/50655436/124353612-23193300-dc3a-11eb-97bb-ced437f5a193.png)

**Comment by victorykong** [comment]
![image](https://user-images.githubusercontent.com/50655436/124353629-417f2e80-dc3a-11eb-91ce-319a93750993.png)

**Comment by TheNorthMemory** [comment]
服务端的nodejs是异步单进程的，这个cpu处理不过来，是程序逻辑问题。。。帮不上你改进程序。。。

不过，建议你可以用一下类似 `pm2` 这样的多进程管理工具，试试看。

**Comment by victorykong** [comment]
是单进程，不是默认会阻塞排队处理吗，这里需要加一些队列解决？
