### ISSUE TITLE
初始化报错，求解答，谢谢

### ISSUE THREAD

**Issue by feichi2016** [TheNorthMemory/wechatpay-axios-plugin#37]
初始化的时候，报
ERROR 438408 nodejs.unhandledRejectionError: Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream
这是什么原因导致的，求助，谢谢

**Comment by TheNorthMemory** [comment]
贴下你的初始化代码

**Comment by Steppenwolf1900** [comment]
老哥，这个问题我也遇到了，你怎么处理的
