### ISSUE TITLE
jsapi下单成功回调在catch里面

### ISSUE THREAD

**Issue by ig666** [TheNorthMemory/wechatpay-axios-plugin#40]
原本应该出现在then里面的回调，出现在catch里面
`    wxpay.v3.pay.transactions.jsapi
      .post(payParames)
      .then((res) => console.log(res,'回调成功'))
      .catch(({response: {status, statusText, data}}) => console.log(status, statusText, data,'回调失败'));`
log打印 undefined undefined {"prepay_id":"---------"} 回调失败

**Comment by ig666** [comment]
好吧，自问自答，看成老版本文档了，用的微信社区里面的文档参照.............

**Comment by TheNorthMemory** [comment]
周5很忙，还要翻墙，头大ing
