### ISSUE TITLE
你好,微信支付平台证书, 这个的配置可以在描述一下么. 

### ISSUE THREAD

**Issue by Dssssds** [TheNorthMemory/wechatpay-axios-plugin#43]
// 「微信支付平台证书」的「证书序列号」，下载器下载后有提示`serial`序列号字段
const platformCertificateSerial = '7132d72a03e93cddf8c03bbd1f37eedf********';
对应的是这个里面的序列号么?
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/17268259/172051808-13affe59-e007-4171-b891-9a207e9926e4.png">

**Comment by TheNorthMemory** [comment]
变量名称 platform certificate serial，翻译出来就是「平台证书序列号」，需要通过SDK内置的下载器手动下载

**Comment by Dssssds** [comment]
好的,谢谢大佬!

**Comment by liuhuapiaoyuan** [comment]
把证书获取单独封装一下 感觉会比较好。。
