### ISSUE TITLE
想弄个证书自动获取发现源码大量的静态函数，静态字段，搞哭了

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [TheNorthMemory/wechatpay-axios-plugin#44]
想弄个证书自动获取发现源码大量的静态函数，静态字段，搞哭了
这样导致实际上只有一个全局的wechatPay，其实new根本就是一个假象
我还没测试过如果系统有多个wechatpay实例 会怎么样

**Comment by TheNorthMemory** [comment]
全局你只需要实例化一次，多商户(multi-tenant)在(APIv2)上支持的不好，APIv3没问题，比如

```js
const instance1 = new Wechatpay({mchid: 1});
const instance2 = new Wechatpay({mchid:2});
```
`instance1` 和 `instance2` 是不同实例，锁定不同`mchid`，其他静态方法是`无状态`设计，按需使用。
