### ISSUE TITLE
正则匹配有个问题，铁子

### ISSUE THREAD

**Issue by sdz123** [TheNorthMemory/wechatpay-axios-plugin#46]
比如下面这串代码：
wxpay.v3.transfer.batches.outBatchNo['1234567899900011'].details.outDetailNo['x16683940311151111X'].get();
后面的outDetailNo参数最后一位X会被正则处理成 ‘-x’;

**Comment by TheNorthMemory** [comment]
`segments` 受如下处理过程约束：

https://github.com/TheNorthMemory/wechatpay-axios-plugin/blob/e6a2cc1b00fdaef148af464cea80c27ff14e8d80/lib/wechatpay.js#L60-L73

你的代码需要微调成：

```js
wxpay.v3.transfer.batches.outBatchNo.$out_batch_no$.details.outDetailNo._out_detail_no_.get({
  out_batch_no: '1234567899900011',
  out_detail_no: 'x16683940311151111X',
})
```

**Comment by sdz123** [comment]
> `segments` 受如下处理过程约束：
> 
> https://github.com/TheNorthMemory/wechatpay-axios-plugin/blob/e6a2cc1b00fdaef148af464cea80c27ff14e8d80/lib/wechatpay.js#L60-L73
> 
> 你的代码需要微调成：
> 
> ```js
> wxpay.v3.transfer.batches.outBatchNo.$out_batch_no$.details.outDetailNo._out_detail_no_.get({
>   out_batch_no: '1234567899900011',
>   out_detail_no: 'x16683940311151111X',
> })
> ```

感谢您的回复！
