### ISSUE TITLE
建议保留微信支付官方的错误码返回

### ISSUE THREAD

**Issue by Zch123** [TheNorthMemory/wechatpay-axios-plugin#48]
建议保留微信官方的错误码返回

**Comment by TheNorthMemory** [comment]
> 建议保留微信官方的错误码返回

https://github.com/TheNorthMemory/wechatpay-axios-plugin/blob/e6a2cc1b00fdaef148af464cea80c27ff14e8d80/lib/utils.js#L47-L66

是个非常好的建议，之前也是困扰了很久，低版本的`axios`确实无能为力，没办法就只能先「备注上：留待后续解决」...

得空我看看怎么调整吧
