### ISSUE TITLE
多商户（实例）相关问题

### ISSUE THREAD

**Issue by swpfY** [TheNorthMemory/wechatpay-axios-plugin#49]
我想在同一个服务中使用两个商户，创建两个实例后，调用前一个实例会返回如下信息（使用API v3）：
```js
{
  code: 'PARAM_ERROR',
  message: 'http header中的mchid与post payload中的mchid不匹配'
}
```
需要说明的是，注释掉后一个实例，使用前一个实例正常。安装依赖版本为：`v0.8.6`
> 不过看到老师您之前说支持多商户 #44，来请教一下

**Comment by TheNorthMemory** [comment]
`v0.x`目前对同一实例下多商户支持的不友好，如果需要使用建议一个实例一个进程，下一个大版本会调整为同一实例支持多商户模式。

**Comment by swpfY** [comment]
明白了，那期待老师下个版本早日发布🚀
