### ISSUE TITLE
根据商户订单号查询微信支付的订单的示例请求

### ISSUE THREAD

**Issue by wisetc** [TheNorthMemory/wechatpay-axios-plugin#50]
如文档中有提及查询微信支付订单的两种方式

> 注意：
> 查询订单可通过[微信支付订单号](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_4_2.shtml#menu1)和[商户订单号](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_4_2.shtml#menu2)两种方式查询，两种查询方式返回结果相同

见 [商户订单号查询](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_4_2.shtml#menu2)

谢谢

**Comment by TheNorthMemory** [comment]
```js
const wxpay = new Wechatpay({});

/* GET /v3/pay/transactions/id/{transaction_id} */
wxpay.v3.pay.transactions.id._transaction_id_.get({
  transaction_id: '1217752501201407033233368018',
  params: {mchid: '1230000109'},
}).then(console.info).catch(console.error);

/* GET /v3/pay/transactions/out-trade-no/{out_trade_no} */
wxpay.v3.pay.transactions.outTradeNo._out_trade_no_.get({
  out_trade_no: '1217752501201407033233368018',
  params: {mchid: '1230000109'},
}).then(console.info).catch(console.error);
```

**Comment by TheNorthMemory** [comment]
甚至可以这样:

```js
wxpay.v3.pay.transactions._kind_._identity_.get({
  kind: 'id', //or 'out-trade-no'
  identity: '1217752501201407033233368018',
  params: { mchid: '1230000109' },
}).then(console.info).catch(console.error);
```

**Comment by wisetc** [comment]
> ```js
> const wxpay = new Wechatpay({});
> 
> /* GET /v3/pay/transactions/id/{transaction_id} */
> wxpay.v3.pay.transactions.id._transaction_id_.get({
>   transaction_id: '1217752501201407033233368018',
>   params: {mchid: '1230000109'},
> }).then(console.info).catch(console.error);
> 
> /* GET /v3/pay/transactions/out-trade-no/{out_trade_no} */
> wxpay.v3.pay.transactions.outTradeNo._out_trade_no_.get({
>   out_trade_no: '1217752501201407033233368018',
>   params: {mchid: '1230000109'},
> }).then(console.info).catch(console.error);
> ```

get it, thank you, 谢谢你的快速回复

**Comment by wisetc** [comment]
@TheNorthMemory 那个属性的 placeholder 是咋实现的，为什么就能访问到这个属性呢

**Comment by TheNorthMemory** [comment]
> @TheNorthMemory 那个属性的 placeholder 是咋实现的，为什么就能访问到这个属性呢

https://github.com/TheNorthMemory/wechatpay-axios-plugin/blob/692e4b3306cc46bdc0541946fb4dd23fdabd12e3/lib/wechatpay.js#L65-L73

https://github.com/TheNorthMemory/wechatpay-axios-plugin/blob/692e4b3306cc46bdc0541946fb4dd23fdabd12e3/lib/decorator.js#L247

**Comment by wisetc** [comment]
> > @TheNorthMemory 那个属性的 placeholder 是咋实现的，为什么就能访问到这个属性呢
> 
> https://github.com/TheNorthMemory/wechatpay-axios-plugin/blob/692e4b3306cc46bdc0541946fb4dd23fdabd12e3/lib/wechatpay.js#L65-L73
> 
> https://github.com/TheNorthMemory/wechatpay-axios-plugin/blob/692e4b3306cc46bdc0541946fb4dd23fdabd12e3/lib/decorator.js#L247

谢谢，明白了
