### ISSUE TITLE
paySign跟JSSDK生成的签名是一样的？

### ISSUE THREAD

**Issue by cssjidi** [TheNorthMemory/wechatpay-axios-plugin#51]

**Comment by TheNorthMemory** [comment]
看不懂你的问题是什么，建议参考官方文档[小程序调起支付的参数需要按照签名规则进行签名计算](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_5_4.shtml)看 `paySign` 计算方法
