### ISSUE TITLE
遇到个问题

### ISSUE THREAD

**Issue by player4sir** [TheNorthMemory/wechatpay-axios-plugin#54]
感谢作者的开源项目，帮了很多忙，await wxpay.v3.profitsharing.orders.post({})  ,在云函数，使用这样调用请求分账，返回{},不知问题出在哪。

**Comment by TheNorthMemory** [comment]
@player4sir 贴一下你的代码样例

**Comment by player4sir** [comment]
感谢您的回复，是这边问题。谢谢您的项目👍
