### ISSUE TITLE
奇怪的post路径

### ISSUE THREAD

**Issue by taoliujun** [TheNorthMemory/wechatpay-axios-plugin#59]
代码是`wxpay.v3.pay.transactions.jsapi.post`，AxiosError报错404，看AxiosError的Request日志，请求的是`path: 'https://api.mch.weixin.qq.com/then'`。

<img width="1385" alt="image" src="https://github.com/user-attachments/assets/d6d5a18c-1edb-47fe-b03c-d0845f8d5191">

**Comment by taoliujun** [comment]
进一步检查发现，是new Wechatpay报的错误。

**Comment by taoliujun** [comment]
已经解决，要移除async。
<img width="503" alt="image" src="https://github.com/user-attachments/assets/985dffe6-8b64-4023-b450-921cb6146123">

**Comment by TheNorthMemory** [comment]
`new Wechatpay` 是同步代码，顾不需要`async`标识符
