### ISSUE TITLE
商户证书是不必要

### ISSUE THREAD

**Issue by xy-peng** [TheNorthMemory/wechatpay-axios-plugin#7]
https://github.com/TheNorthMemory/wechatpay-axios-plugin/blob/38534fb578887cff8123fef231ab26d7f3d7f5e8/lib/interceptor.js#L25

如果要求调用方传入了证书序列号的话，就不需要传入商户证书了

**Comment by TheNorthMemory** [comment]
其实这里是有个疑问的，我忍着没给 官方 `Java` 及 `PHP` 版开issue, 这里需要仔细思考下，貌似是有安全隐患的（例如：商户证书泄露，签名回调通知可以是非官方签名通知）

**Comment by TheNorthMemory** [comment]
done
